//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalWebsite_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class application
    {
        public int application_id { get; set; }
        public int job_id { get; set; }
        public int job_seeker_id { get; set; }
        public string cover_letter { get; set; }
        public string resume { get; set; }
        public System.DateTime applied_date { get; set; }
    }
}
