//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalWebsite_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interview
    {
        public int interview_id { get; set; }
        public int application_id { get; set; }
        public int interviewer_id { get; set; }
        public System.DateTime interview_date { get; set; }
        public System.TimeSpan interview_time { get; set; }
        public string interview_location { get; set; }
        public string interview_notes { get; set; }
    }
}
