//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalWebsite_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_seeker
    {
        public int job_seeker_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public string address { get; set; }
        public string education_level { get; set; }
        public int experience { get; set; }
        public string resume { get; set; }
    }
}
