//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalWebsite_WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobPortalWebsite2 : DbContext
    {
        public JobPortalWebsite2()
            : base("name=JobPortalWebsite2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<application> applications { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<interview> interviews { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<job_seeker> job_seeker { get; set; }
        public virtual DbSet<message> messages { get; set; }
    }
}
