//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalWebsite1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppliedJobsTable
    {
        public int AppliedJobId { get; set; }
        public Nullable<int> Jobseeker_Id { get; set; }
        public Nullable<int> Jobseeker_jobId { get; set; }
        public string UploadResume { get; set; }
        public Nullable<int> companyId { get; set; }
    
        public virtual CompanyTable CompanyTable { get; set; }
        public virtual JobSeekertable JobSeekertable { get; set; }
        public virtual JobPostTable JobPostTable { get; set; }
    }
}
