//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalWebsite1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyTable()
        {
            this.AppliedJobsTables = new HashSet<AppliedJobsTable>();
            this.JobPostTables = new HashSet<JobPostTable>();
        }
    
        public int companyId { get; set; }
        public string companyname { get; set; }
        public string companyemail { get; set; }
        public string companyphone { get; set; }
        public string companyaddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppliedJobsTable> AppliedJobsTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPostTable> JobPostTables { get; set; }
    }
}
