//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalWebsite1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobPortalWebsiteEntities : DbContext
    {
        public JobPortalWebsiteEntities()
            : base("name=JobPortalWebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTable> AdminTables { get; set; }
        public virtual DbSet<AppliedJobsTable> AppliedJobsTables { get; set; }
        public virtual DbSet<CompanyTable> CompanyTables { get; set; }
        public virtual DbSet<JobPostTable> JobPostTables { get; set; }
        public virtual DbSet<JobSeekertable> JobSeekertables { get; set; }
    }
}
