//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalWebsite1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPostTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPostTable()
        {
            this.AppliedJobsTables = new HashSet<AppliedJobsTable>();
        }
    
        public int Jobseeker_jobId { get; set; }
        public string Jobseeker_jobTitle { get; set; }
        public string Jobseeker_description { get; set; }
        public string Jobseeker_experienceLevel { get; set; }
        public string Jobseeker_skillSet { get; set; }
        public string Jobseeker_payScale { get; set; }
        public string Jobseeker_location { get; set; }
        public string Jobseeker_jobType { get; set; }
        public string Jobseeker_jobStatus { get; set; }
        public Nullable<System.DateTime> Jobseeker_startDate { get; set; }
        public Nullable<System.DateTime> Jobseeker_lastDate { get; set; }
        public Nullable<int> companyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppliedJobsTable> AppliedJobsTables { get; set; }
        public virtual CompanyTable CompanyTable { get; set; }
    }
}
